export const Cards = [
  {
    img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTSz_1a_TPF2rJDxs8TCdb92-rFQkVISnkFqQ&usqp=CAU",
    image: "../../../../../Assets/burger.png",
    title: "Juice - Isometric Silver",
    Age: 23,
    Skills: "Coding, Logic and Bluntness, and pretty Patient",
    Gender: "M",
    Ethnicity: "Black",
    Flavour: "sweet",
    Brand: "Juice",
  },
  {
    img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR-EJ9tRARHhotbzA2nlAA8eOKTdVrV8OGOEg&usqp=CAU",
    image: "../../../../../Assets/chris-hardy-y4Atz4olpAQ-unsplash.jpg",
    title: "Juice - Earnest Gold",
    Age: 23,
    Skills: "Physiotherapy, Texting A lot and Stickler for the rules",
    Gender: "F",
    Ethnicity: "White",
    Flavour: "sweet",
    Brand: "Juice",
  },
  {
    img:
      "https://image.freepik.com/free-photo/swiss-watches-black-background_99272-23.jpg",
    image: "../../../../../Assets/heather-zabriskie-yBzrPGLjMQw-unsplash.jpg",
    title: "Pearl - Stainless Steel",
    Age: 41,
    Skills: "Law, Communication, Bending the Law",
    Gender: "M",
    Ethnicity: "White",
    Flavour: "sweet",
    Brand: "Pearl",
  },
  {
    img:
      "https://image.freepik.com/free-photo/swiss-watches-black-background_99272-36.jpg",
    image: "../../../../../Assets/jess-bailey-DXd6X3wuRA0-unsplash.jpg",
    title: "Pearl - Isometric Silver",
    Age: 30,
    Skills: "Photogenic Memory, Idealist, fantasist",
    Gender: "M",
    Ethnicity: "White",
    Flavour: "sweet",
    Brand: "Pearl",
  },
  {
    img: "https://miro.medium.com/max/4096/1*66PlU6sokCqMoE3p-gLJ6w.jpeg",
    image: "../../../../../Assets/lukas-blazek-UAvYasdkzq8-unsplash.jpg",
    title: "Juice - Chronograph",
    Age: 55,
    Skills: "Pathologist, Inspirer, Hard Worker",
    Gender: "F",
    Ethnicity: "Black",
    Flavour: "sweet",
    Brand: "Juice",
  },
  {
    img: "https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX11895566.jpg",
    image: "../../../../..//Assets/mike-petrucci-noC8N68eYN8-unsplash.jpg",
    title: "Pearl - Chronograph",
    Age: 43,
    Skills: "Driving Quickly, Communication, Purchasing expensive things",
    Gender: "M",
    Ethnicity: "Black",
    Flavour: "sweet",
    Brand: "Pearl",
  },
  {
    img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRxMZpDICYvExjeg4ZCaLzUv12XM1fhslxGNQ&usqp=CAU",
    image: "../../../../..//Assets/mike-petrucci-noC8N68eYN8-unsplash.jpg",
    title: "Zealium - Stainless Steel",
    Age: 41,
    Skills: "Comedian, Inspirer, Actor, Professional",
    Gender: "M",
    Ethnicity: "Black",
    Flavour: "sweet",
    Brand: "Zealium",
  },
  {
    img:
      "https://image.freepik.com/free-photo/swiss-watches-black-background_99272-25.jpg",
    image: "../../../../..//Assets/mike-petrucci-noC8N68eYN8-unsplash.jpg",
    title: "Zealium - White Gold",
    Age: 58,
    Skills: "Loyalty, Knowledge of Law, Procastination",
    Gender: "M",
    Ethnicity: "Black",
    Flavour: "sweet",
    Brand: "Zealium",
  },
  {
    img:
      "https://us.123rf.com/450wm/magryt/magryt1412/magryt141200040/34527869-swiss-watches-on-black-background-product-photography.jpg?ver=6",
    image: "../../../../..//Assets/mike-petrucci-noC8N68eYN8-unsplash.jpg",
    title: "Zealium - Chronograph",
    Age: 81,
    Skills: "Leadership, Communication, Conservatism",
    Gender: "M",
    Ethnicity: "white",
    Flavour: "sweet",
    Brand: "Zealium",
  },
  {
    img:
      "https://us.123rf.com/450wm/magryt/magryt1507/magryt150700065/42479159-swiss-watches-on-black-background-product-photography.jpg?ver=6",
    image: "../../../../..//Assets/mike-petrucci-noC8N68eYN8-unsplash.jpg",
    title: "Juice - Titanium ",
    Age: 36,
    Skills: "Coding, Dollardollar bills, Facebook",
    Gender: "M",
    Ethnicity: "White",
    Flavour: "sour",
    Brand: "Juice",
  },
  {
    img:
      "https://cdn.shopify.com/s/files/1/0136/8273/7209/files/newhands-fronthero_1600x.jpg?v=1554222884",
    image: "../../../../..//Assets/mike-petrucci-noC8N68eYN8-unsplash.jpg",
    title: "Pearl - Stainless Steel",
    Age: 36,
    Skills: "Singing, Good Looks, X-factor",
    Gender: "F",
    Ethnicity: "Black",
    Flavour: "sour",
    Brand: "Pearl",
  },
  {
    img:
      "https://us.123rf.com/450wm/magryt/magryt1411/magryt141100068/34053375-swiss-watches-on-black-background-product-photography.jpg?ver=6",
    image: "../../../../..//Assets/mike-petrucci-noC8N68eYN8-unsplash.jpg",
    title: "Juice - White Gold",
    Age: 81,
    Skills: "Equal Rights, Communication, Strength, Character",
    Gender: "F",
    Ethnicity: "Black",
    Flavour: "sour",
    Brand: "Juice",
  },
  {
    img:
      "https://us.123rf.com/450wm/magryt/magryt1507/magryt150700074/42482585-swiss-watches-on-black-background-product-photography.jpg?ver=6",
    image: "../../../../..//Assets/mike-petrucci-noC8N68eYN8-unsplash.jpg",
    title: "Zealium - White Gold",
    Age: 72,
    Skills: "Driving Quickly, Communication, Purchasing expensive things",
    Gender: "F",
    Ethnicity: "White",
    Flavour: "sour",
    Brand: "Zealium",
  },
  {
    img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR-EJ9tRARHhotbzA2nlAA8eOKTdVrV8OGOEg&usqp=CAU",
    image: "../../../../..//Assets/mike-petrucci-noC8N68eYN8-unsplash.jpg",
    title: "Juice - Chronograph",
    Age: 41,
    Skills: "Pouting, No skills, Acting",
    Gender: "F",
    Ethnicity: "White",
    Flavour: "sour",
    Brand: "Juice",
  },
]
